import random
import time

acronym = [
		"3DES",
		"AAA",
		"ABAC",
		"ACL",
		"AES",
		"AES256",
		"AH",
		"ALE",
		"AP",
		"API",
		"APT",
		"ARO",
		"ARP",
		"ASLR",
		"ASP",
		"AUP",
		"AV",
		"AV",
		"BAC",
		"BCP",
		"BIA",
		"BIOS",
		"BPA",
		"BPDU",
		"BYOD",
		"CA",
		"CAC",
		"CAN",
		"CAPTCHA",
		"Test",
		"CAR",
		"CBC",
		"CCMP",
		"CCTV",
		"CER",
		"ACRONYM",
		"CER",
		"CERT",
		"CFB",
		"CHAP",
		"CIO",
		"CIRT",
		"CMS",
		"COOP",
		"COPE",
		"CP",
		"CRC",
		"CRL",
		"CSIRT",
		"CSO",
		"CSP",
		"CSR",
		"CSRF",
		"CSU",
		"CTM",
		"CTO",
		"CTR",
		"CYOD",
		"DAC",
		"DBA",
		"DDoS",
		"DEP",
		"DER",
		"DES",
		"DFIR",
		"DHCP",
		"DHE",
		"DHE",
		"DLL",
		"DLP",
		"DMZ",
		"DNAT",
		"DNS",
		"DoS",
		"DRP",
		"DSA",
		"DSL",
		"DSU",
		"EAP",
		"ECB",
		"ECC",
		"ECDHE",
		"ECDSA",
		"EFS",
		"EMI",
		"EMP",
		"ERP",
		"ESN",
		"ESP",
		"EF",
		"FACL",
		"FAR",
		"FDE",
		"FRR",
		"FTP",
		"FTPS",
		"GCM",
		"GPG",
		"GPO",
		"GPS",
		"GPU",
		"GRE",
		"HA",
		"HDD",
		"HIDS",
		"HIPS",
		"HMAC",
		"HOTP",
		"HSM",
		"HTML",
		"HTTP",
		"HTTPS",
		"HVAC",
		"IaaS",
		"ICMP",
		"ICS",
		"ID",
		"IDEA",
		"IDF",
		"IdP",
		"IDS",
		"IEEE",
		"IIS",
		"IKE",
		"IM",
		"IMAP4",
		"IoT",
		"IP",
		"IPSec",
		"IR",
		"IR",
		"IRC",
		"IRP",
		"ISA",
		"ISP",
		"ISSO",
		"ITCP",
		"IV",
		"KDC",
		"KEK",
		"L2TP",
		"LAN",
		"LDAP",
		"LEAP",
		"MaaS",
		"MAC",
		"MAC",
		"MAC",
		"MAN",
		"MBR",
		"MD5",
		"MDF",
		"MDM",
		"MFA",
		"MFD",
		"MITM",
		"MMS",
		"MOA",
		"MOU",
		"MPLS",
		"MSCHAP",
		"Authentication",
		"MSP",
		"MTBF",
		"MTTF",
		"MTTR",
		"MTU",
		"NAC",
		"NAT",
		"NDA",
		"NFC",
		"NGAC",
		"NIDS",
		"NIPS",
		"NIST",
		"NTFS",
		"NTLM",
		"NTP",
		"OAUTH",
		"OCSP",
		"OID",
		"OS",
		"OTA",
		"OVAL",
		"P12",
		"P2P",
		"PaaS",
		"PAC",
		"PAM",
		"PAP",
		"PAT",
		"PBKDF2",
		"PBX",
		"PCAP",
		"PEAP",
		"PED",
		"PEM",
		"PFS",
		"PFX",
		"PGP",
		"PHI",
		"PII",
		"PIV",
		"PKI",
		"POODLE",
		"POP",
		"POTS",
		"PPP",
		"PPTP",
		"PSK",
		"PTZ",
		"RA",
		"RA",
		"RAD",
		"RADIUS",
		"RAID",
		"RAS",
		"RAT",
		"RBAC",
		"RBAC",
		"RC4",
		"RDP",
		"RFID",
		"RIPEMD",
		"Evaluation",
		"ROI",
		"RMF",
		"RPO",
		"RSA",
		"RTBH",
		"RTO",
		"RTOS",
		"RTP",
		"S/MIME",
		"SaaS",
		"SAML",
		"SAN",
		"SAN",
		"SCADA",
		"SCAP",
		"SCEP",
		"SCP",
		"SCSI",
		"SDK",
		"SDLC",
		"SDLM",
		"SDN",
		"SED",
		"SEH",
		"SFTP",
		"SHA",
		"SHTTP",
		"SIEM",
		"SIM",
		"SLA",
		"SLE",
		"SMB",
		"SMS",
		"SMTP",
		"SMTPS",
		"SNMP",
		"SOAP",
		"SoC",
		"SPF",
		"SPIM",
		"SPoF",
		"SQL",
		"SRTP",
		"SSD",
		"SSH",
		"SSID",
		"SSL",
		"SSO",
		"STP",
		"TACACS+",
		"Control",
		"TCP/IP",
		"TGT",
		"TKIP",
		"TLS",
		"TOTP",
		"TPM",
		"TSIG",
		"UAT",
		"UAV",
		"UDP",
		"UEFI",
		"UPS",
		"URI",
		"URL",
		"USB",
		"USB",
		"UTM",
		"UTP",
		"VDE",
		"VDI",
		"VLAN",
		"VLSM",
		"VM",
		"VoIP",
		"VPN",
		"VTC",
		"WAF",
		"WAP",
		"WEP",
		"WIDS",
		"WIPS",
		"WORM",
		"WPA",
		"WPA2",
		"WPS",
		"WTLS",
		"XML",
		"XOR",
		"XSRF",
		"XSS"
]

definition = [
		"Triple Digital Encryption Standard",
		"Authentication Authorization and Accounting",
		"Attribute-based Access Control",
		"Access Control List",
		"Advanced Encryption Standard",
		"Advanced Encryption Standards 256bit",
		"Authentication Header",
		"Annualized Loss Expectancy",
		"Access Point",
		"Application Programming Interface",
		"Advanced Persistent Threat",
		"Annualized Rate of Occurrence",
		"Address Resolution Protocol",
		"Address Space Layout Randomization",
		"Application Service Provider",
		"Acceptable Use Policy",
		"Antivirus",
		"Asset Value",
		"Business Availability Center",
		"Business Continuity Planning",
		"Business Impact Analysis",
		"Basic Input/Output System",
		"Business Partners Agreement",
		"Bridge Protocol Data Unit",
		"Bring Your Own Device",
		"Certificate Authority",
		"Common Access Card",
		"Controller Area Network",
		"Completely Automated Public Turing",
		"to Tell Computers and Humans Apart",
		"Corrective Action Report",
		"Cipher Block Chaining",
		"Counter-Mode/CBC-Mac Protocol",
		"Closed-circuit Television",
		"Certificate",
		"SPELLED OUT",
		"Cross-over Error Rate",
		"Computer Emergency Response Team",
		"Cipher Feedback",
		"Challenge Handshake Authentication Protocol",
		"Chief Information Officer",
		"Computer Incident Response Team",
		"Content Management System",
		"Continuity of Operations Plan",
		"Corporate Owned Personally Enabled",
		"Contingency Planning",
		"Cyclical Redundancy Check",
		"Certificate Revocation List",
		"Computer Security Incident Response Team",
		"Chief Security Officer",
		"Cloud Service Provider",
		"Certificate Signing Request",
		"Cross-site Request Forgery",
		"Channel Service Unit",
		"Counter-Mode",
		"Chief Technology Officer",
		"Counter",
		"Choose Your Own Device",
		"Discretionary Access Control",
		"Database Administrator",
		"Distributed Denial of Service",
		"Data Execution Prevention",
		"Distinguished Encoding Rules",
		"Digital Encryption Standard",
		"Digital Forensics and Investigation Response",
		"Dynamic Host Configuration Protocol",
		"Data-Handling Electronics",
		"Diffie-Hellman Ephemeral",
		"Dynamic Link Library",
		"Data Loss Prevention",
		"Demilitarized Zone",
		"Destination Network Address Transaction",
		"Domain Name Service (Server)",
		"Denial of Service",
		"Disaster Recovery Plan",
		"Digital Signature Algorithm",
		"Digital Subscriber Line",
		"Data Service Unit",
		"Extensible Authentication Protocol",
		"Electronic Code Book",
		"Elliptic Curve Cryptography",
		"Elliptic Curve Diffie-Hellman Ephemeral",
		"Elliptic Curve Digital Signature Algorithm",
		"Encrypted File System",
		"Electromagnetic Interference",
		"Electro Magnetic Pulse",
		"Enterprise Resource Planning",
		"Electronic Serial Number",
		"Encapsulated Security Payload",
		"Exposure Factor",
		"File System Access Control List",
		"False Acceptance Rate",
		"Full Disk Encryption",
		"False Rejection Rate",
		"File Transfer Protocol",
		"Secured File Transfer Protocol",
		"Galois Counter Mode",
		"Gnu Privacy Guard",
		"Group Policy Object",
		"Global Positioning System",
		"Graphic Processing Unit",
		"Generic Routing Encapsulation",
		"High Availability",
		"Hard Disk Drive",
		"Host-based Intrusion Detection System",
		"Host-based Intrusion Prevention System",
		"Hashed Message Authentication Code",
		"HMAC-based One-Time Password",
		"Hardware Security Module",
		"Hypertext Markup Language",
		"Hypertext Transfer Protocol",
		"Hypertext Transfer Protocol over SSL/TLS",
		"Heating Ventilation and Air Conditioning",
		"Infrastructure as a Service",
		"Internet Control Message Protocol",
		"Industrial Control Systems",
		"Identification",
		"International Data Encryption Algorithm",
		"Intermediate Distribution Frame",
		"Identity Provider",
		"Intrusion Detection System",
		"Institute of Electrical and Electronic Engineers",
		"Internet Information System",
		"Internet Key Exchange",
		"Instant Messaging",
		"Internet Message Access Protocol v4",
		"Internet of Things",
		"Internet Protocol",
		"Internet Protocol Security",
		"Incident Response",
		"Infrared",
		"Internet Relay Chat",
		"Incident Response Plan",
		"Interconnection Security Agreement",
		"Internet Service Provider",
		"Information Systems Security Officer",
		"IT Contingency Plan",
		"Initialization Vector",
		"Key Distribution Center",
		"Key Encryption Key",
		"Layer 2 Tunneling Protocol",
		"Local Area Network",
		"Lightweight Directory Access Protocol",
		"Lightweight Extensible Authentication Protocol",
		"Monitoring as a Service",
		"Mandatory Access Control",
		"Media Access Control",
		"Message Authentication Code",
		"Metropolitan Area Network",
		"Master Boot Record",
		"Message Digest 5",
		"Main Distribution Frame",
		"Mobile Device Management",
		"Multi-Factor Authentication",
		"Multi-function Device",
		"Man-in-the-Middle",
		"Multimedia Message Service",
		"Memorandum of Agreement",
		"Memorandum of Understanding",
		"Multi-protocol Label Switching",
		"Microsoft Challenge Handshake",
		"Protocol",
		"Managed Service Provider",
		"Mean Time Between Failures",
		"Mean Time to Failure",
		"Mean Time to Recover or Mean Time to Repair",
		"Maximum Transmission Unit",
		"Network Access Control",
		"Network Address Translation",
		"Non-disclosure Agreement",
		"Near Field Communication",
		"Next Generation Access Control",
		"Network-based Intrusion Detection System",
		"Network-based Intrusion Prevention System",
		"National Institute of Standards & Technology",
		"New Technology File System",
		"New Technology LAN Manager",
		"Network Time Protocol",
		"Open Authorization",
		"Online Certificate Status Protocol",
		"Object Identifier",
		"Operating System",
		"Over The Air",
		"Open Vulnerability Assessment Language",
		"PKCS #12",
		"Peer to Peer",
		"Platform as a Service",
		"Proxy Auto Configuration",
		"Pluggable Authentication Modules",
		"Password Authentication Protocol",
		"Port Address Translation",
		"Password-based Key Derivation Function 2",
		"Private Branch Exchange",
		"Packet Capture",
		"Protected Extensible Authentication Protocol",
		"Personal Electronic Device",
		"Privacy-enhanced Electronic Mail",
		"Perfect Forward Secrecy",
		"Personal Exchange Format",
		"Pretty Good Privacy",
		"Personal Health Information",
		"Personally Identifiable Information",
		"Personal Identity Verification",
		"Public Key Infrastructure",
		"Padding Oracle on Downgrade Legacy Encryption",
		"Post Office Protocol",
		"Plain Old Telephone Service",
		"Point-to-Point Protocol",
		"Point-to-Point Tunneling Protocol",
		"Pre-shared Key",
		"Pan-Tilt-Zoom",
		"Recovery Agent",
		"Registration Authority",
		"Rapid Application Development",
		"Remote Authentication Dial-in User Server",
		"Redundant Array of Inexpensive Disks",
		"Remote Access Server",
		"Remote Access Trojan",
		"Role-based Access Control",
		"Rule-based Access Control",
		"Rivest Cipher version 4",
		"Remote Desktop Protocol",
		"Radio Frequency Identifier",
		"RACE Integrity Primitives",
		"Message Digest",
		"Return on Investment",
		"Risk Management Framework",
		"Recovery Point Objective",
		"Rivest Shamir & Adleman",
		"Remotely Triggered Black Hole",
		"Recovery Time Objective",
		"Real-time Operating System",
		"Real-time Transport Protocol",
		"Secure/Multipurpose Internet Mail Extensions",
		"Software as a Service",
		"Security Assertions Markup Language",
		"Storage Area Network",
		"Subject Alternative Name",
		"System Control and Data Acquisition",
		"Security Content Automation Protocol",
		"Simple Certificate Enrollment Protocol",
		"Secure Copy",
		"Small Computer System Interface",
		"Software Development Kit",
		"Software Development Life Cycle",
		"Software Development Life Cycle Methodology",
		"Software Defined Network",
		"Self-encrypting Drive",
		"Structured Exception Handler",
		"Secured File Transfer Protocol",
		"Secure Hashing Algorithm",
		"Secure Hypertext Transfer Protocol",
		"Security Information and Event Management",
		"Subscriber Identity Module",
		"Service Level Agreement",
		"Single Loss Expectancy",
		"Server Message Block",
		"Short Message Service",
		"Simple Mail Transfer Protocol",
		"Simple Mail Transfer Protocol Secure",
		"Simple Network Management Protocol",
		"Simple Object Access Protocol",
		"System on Chip",
		"Sender Policy Framework",
		"Spam over Internet Messaging",
		"Single Point of Failure",
		"Structured Query Language",
		"Secure Real-Time Protocol",
		"Solid State Drive",
		"Secure Shell",
		"Service Set Identifier",
		"Secure Sockets Layer",
		"Single Sign-on",
		"Shielded Twisted Pair",
		"Terminal Access Controller Access",
		"System Plus",
		"Transmission Control Protocol/Internet Protocol",
		"Ticket Granting Ticket",
		"Temporal Key Integrity Protocol",
		"Transport Layer Security",
		"Time-based One-time Password",
		"Trusted Platform Module",
		"Transaction Signature",
		"User Acceptance Testing",
		"Unmanned Aerial Vehicle",
		"User Datagram Protocol",
		"Unified Extensible Firmware Interface",
		"Uninterruptable Power Supply",
		"Uniform Resource Identifier",
		"Universal Resource Locator",
		"Universal Serial Bus",
		"OTG USB On The Go",
		"Unified Threat Management",
		"Unshielded Twisted Pair",
		"Virtual Desktop Environment",
		"Virtual Desktop Infrastructure",
		"Virtual Local Area Network",
		"Variable Length Subnet Masking",
		"Virtual Machine",
		"Voice over IP",
		"Virtual Private Network",
		"Video Teleconferencing",
		"Web Application Firewall",
		"Wireless Access Point",
		"Wired Equivalent Privacy",
		"Wireless Intrusion Detection System",
		"Wireless Intrusion Prevention System",
		"Write Once Read Many",
		"WiFi Protected Access",
		"WiFi Protected Access 2",
		"WiFi Protected Setup",
		"Wireless TLS",
		"Extensible Markup Language",
		"Exclusive Or",
		"Cross-site Request Forgery",
		"Cross-site Scripting",

]

while(1):

	x = random.randint(0,315)
	
	print(acronym[x])

	time.sleep(3)

	print(definition[x])


