
var = "3DES AAA ABAC ACL AES AES256 AH ALE AP API APT ARO ARP ASLR ASP AUP AV AV BAC BCP BIA BIOS BPA BPDU BYOD CA CAC CAN CAPTCHA Test CAR CBC CCMP CCTV CER ACRONYM CER CERT CFB CHAP CIO CIRT CMS COOP COPE CP CRC CRL CSIRT CSO CSP CSR CSRF CSU CTM CTO CTR CYOD DAC DBA DDoS DEP DER DES DFIR DHCP DHE DHE DLL DLP DMZ DNAT DNS DoS DRP DSA DSL DSU EAP ECB ECC ECDHE ECDSA EFS EMI EMP ERP ESN ESP EF FACL FAR FDE FRR FTP FTPS GCM GPG GPO GPS GPU GRE HA HDD HIDS HIPS HMAC HOTP HSM HTML HTTP HTTPS HVAC IaaS ICMP ICS ID IDEA IDF IdP IDS IEEE IIS IKE IM IMAP4 IoT IP IPSec IR IR IRC IRP ISA ISP ISSO ITCP IV KDC KEK L2TP LAN LDAP LEAP MaaS MAC MAC MAC MAN MBR MD5 MDF MDM MFA MFD MITM MMS MOA MOU MPLS MSCHAP Authentication MSP MTBF MTTF MTTR MTU NAC NAT NDA NFC NGAC NIDS NIPS NIST NTFS NTLM NTP OAUTH OCSP OID OS OTA OVAL P12 P2P PaaS PAC PAM PAP PAT PBKDF2 PBX PCAP PEAP PED PEM PFS PFX PGP PHI PII PIV PKI POODLE POP POTS PPP PPTP PSK PTZ RA RA RAD RADIUS RAID RAS RAT RBAC RBAC RC4 RDP RFID RIPEMD Evaluation ROI RMF RPO RSA RTBH RTO RTOS RTP S/MIME SaaS SAML SAN SAN SCADA SCAP SCEP SCP SCSI SDK SDLC SDLM SDN SED SEH SFTP SHA SHTTP SIEM SIM SLA SLE SMB SMS SMTP SMTPS SNMP SOAP SoC SPF SPIM SPoF SQL SRTP SSD SSH SSID SSL SSO STP TACACS+ Control TCP/IP TGT TKIP TLS TOTP TPM TSIG UAT UAV UDP UEFI UPS URI URL USB USB UTM UTP VDE VDI VLAN VLSM VM VoIP VPN VTC WAF WAP WEP WIDS WIPS WORM WPA WPA2 WPS WTLS XML XOR XSRF XSS"

work = var.split()

for i in range(len(work)):

	print('"' + work[i] + '"' + ',')
